### ISSUE TITLE
100.0.0.1287-beta of package Esri.ArcGISRuntime.Xamarin not found

### ISSUE THREAD

**Issue by steveoh** [Esri/arcgis-runtime-samples-xamarin#41]
It appears this nuget package was removed?

![image](https://cloud.githubusercontent.com/assets/325813/14300505/07ee8788-fb4e-11e5-9bc6-6931295a1839.png)

**Comment by zwaap** [comment]
The package is not published to nuget.org due to size restrictions.  Running the VSIX (available [here](https://earlyadopter.esri.com/project/version/default.html?cap=4DBE143A73CC4E629BA34DDE5090139C&arttypeid={34026E8A-B96A-400E-8259-BBBBD18722F5})) installs the package locally, after which the package restore operation should be able to find it.

**Comment by steveoh** [comment]
I have installed that and it did not add the new nuget package source or the dll locally.

**Comment by mbranscomb** [comment]
@steveoh Please can you raise this in the [early adopter forum](https://earlyadopter.esri.com/project/forum/default.html?cap=4DBE143A73CC4E629BA34DDE5090139C) with details of your OS, IDE, etc and the steps you went through to install the VSIX and acquire the samples repo? We'll investigate.

Cheers

**Comment by steveoh** [comment]
Thanks, it appears as [this](https://earlyadopter.esri.com/project/forum/thread.html?cap=4DBE143A73CC4E629BA34DDE5090139C&forid={13603BAE-F23D-4166-B8C0-24B5134BA454}&topid={95A53073-93F3-482E-A910-7AB69EB7E396}) might be the same issue I am encountering. I'll post there.
